In [20]:
fruit_prices = {
    'apple': 0.65,
    'mango': 1.50,
    'strawberry': '$5/pint',
    'durian' : 'unavailable'
}

In [21]:
fruit_prices['apple']

0.65

In [23]:
fruit_prices['apple'] =1.00
fruit_prices

{'apple': 1.0,
 'mango': 1.5,
 'strawberry': '$5/pint',
 'durian': 'unavailable',
 'pear': 1.0}

In [25]:
a = 0
b = 0

if a> b:
    print('a is greater than b')
elif a == b:
    print('a is equal to b')
else:
    print('a is not greater than b')

a is equal to b


In [27]:
random_stuff
for element in random_stuff:
    print(element)

ten
0.1
banana
4.0


In [29]:
double_stuff = [element * 2 for element in random_stuff]
double_stuff

['tenten', 0.2, 'bananabanana', 8.0]

In [30]:
counter = 0
while counter < 5:
    print(counter)
    counter = counter +1

0
1
2
3
4


In [31]:
# import..
import math
print(math.pi)

3.141592653589793


In [32]:
# from .. import ..
from math import pi
print(pi)

3.141592653589793


In [33]:
# from .. import .. as ..
from math import pi as PI
print(PI)

3.141592653589793


In [34]:
# We'll need the random module for this
import random

def add_noise(x, mu, sd):
    """
    Adds gaussian noise to the input.
    
    Parameters
    ----------
    x : number
        The number to add noise to
    mu : float
        the mean of the gaussian noise distribution
    sd : float
        The standard deviation of the noise distribution
    """
    noisy = random.normalvariate(mu, sd) + x
    return noisy

In [35]:
x = add_noise(10, 0, 1)
print(x)

10.449114916674228


In [36]:
def add_noise_with_defaults(x, mu=0, sd=1):
    """
    Adds gaussian noise to the input.
    
    Parameters
    ----------
    x : number
        The number to add noise to
    mu : float, optional
        the mean of the gaussian noise distribution. Default: 0
    sd : float, optional
        The standard deviation of the noise distribution. Default: 1
    """
    noisy = random.normalvariate(mu, sd) + x
    return noisy

In [43]:
add_noise_with_defaults(10, 10, 10)

17.402045653577147

In [45]:
%time 2*2

CPU times: user 2 µs, sys: 2 µs, total: 4 µs
Wall time: 6.91 µs


4

In [50]:
# Average time running the code
%timeit 2 * 2

12.9 ns ± 0.0819 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [51]:
import numpy
numpy.reshape?

In [52]:
# By convention, we assign numpy to the variable np for brevity
import numpy as np

In [53]:
# Create an empty 10 x 10 array of zeros
array_zeros = np.zeros(shape=(10,10))
print(array_zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [54]:
# Inspect the array: what can we learn about its dimentionality?
print(array_zeros.shape)

(10, 10)


In [55]:
# Its data type?
print(array_zeros.dtype)

float64


In [57]:
# Create a 1D numpy array with values 0 through 999
array_1d = np.arange(0,1000)
array_1d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [58]:
# Reshape our array to 100 x 10
array_2d = np.reshape(array_1d, (100,10))
array_2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [59]:
# Multiply every value in our array by 2
array_times_2 = array_2d * 2
array_times_2

array([[   0,    2,    4,    6,    8,   10,   12,   14,   16,   18],
       [  20,   22,   24,   26,   28,   30,   32,   34,   36,   38],
       [  40,   42,   44,   46,   48,   50,   52,   54,   56,   58],
       [  60,   62,   64,   66,   68,   70,   72,   74,   76,   78],
       [  80,   82,   84,   86,   88,   90,   92,   94,   96,   98],
       [ 100,  102,  104,  106,  108,  110,  112,  114,  116,  118],
       [ 120,  122,  124,  126,  128,  130,  132,  134,  136,  138],
       [ 140,  142,  144,  146,  148,  150,  152,  154,  156,  158],
       [ 160,  162,  164,  166,  168,  170,  172,  174,  176,  178],
       [ 180,  182,  184,  186,  188,  190,  192,  194,  196,  198],
       [ 200,  202,  204,  206,  208,  210,  212,  214,  216,  218],
       [ 220,  222,  224,  226,  228,  230,  232,  234,  236,  238],
       [ 240,  242,  244,  246,  248,  250,  252,  254,  256,  258],
       [ 260,  262,  264,  266,  268,  270,  272,  274,  276,  278],
       [ 280,  282,  284,  286,  2

In [60]:
# Innspect the first 2 elements of each of the first five rows
array_times_2[:5, :2]

array([[ 0,  2],
       [20, 22],
       [40, 42],
       [60, 62],
       [80, 82]])

In [63]:
original = np.copy(array_times_2)
original

array([[   0,    2,    4,    6,    8,   10,   12,   14,   16,   18],
       [  20,   22,   24,   26,   28,   30,   32,   34,   36,   38],
       [  40,   42,   44,   46,   48,   50,   52,   54,   56,   58],
       [  60,   62,   64,   66,   68,   70,   72,   74,   76,   78],
       [  80,   82,   84,   86,   88,   90,   92,   94,   96,   98],
       [ 100,  102,  104,  106,  108,  110,  112,  114,  116,  118],
       [ 120,  122,  124,  126,  128,  130,  132,  134,  136,  138],
       [ 140,  142,  144,  146,  148,  150,  152,  154,  156,  158],
       [ 160,  162,  164,  166,  168,  170,  172,  174,  176,  178],
       [ 180,  182,  184,  186,  188,  190,  192,  194,  196,  198],
       [ 200,  202,  204,  206,  208,  210,  212,  214,  216,  218],
       [ 220,  222,  224,  226,  228,  230,  232,  234,  236,  238],
       [ 240,  242,  244,  246,  248,  250,  252,  254,  256,  258],
       [ 260,  262,  264,  266,  268,  270,  272,  274,  276,  278],
       [ 280,  282,  284,  286,  2

In [66]:
# Load the dataset at https://bit.ly/nds-python-pure
data = np.loadtxt('https://bit.ly/nds-python-pure')
print(data)
print(data.shape)
print(data.dtype)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]
(506, 14)
float64


In [70]:
# Take the mean of the data array
print(data.mean())
print(np.mean(data))

66.67816985036703
66.67816985036703


In [68]:
# Take the mean across the *first axis* (i.e., the mean across rows)
data.mean(axis=0)

array([3.61352356e+00, 1.13636364e+01, 1.11367787e+01, 6.91699605e-02,
       5.54695059e-01, 6.28463439e+00, 6.85749012e+01, 3.79504269e+00,
       9.54940711e+00, 4.08237154e+02, 1.84555336e+01, 3.56674032e+02,
       1.26530632e+01, 2.25328063e+01])

In [71]:
# Standard deviation
print(data.std(axis=0))

[8.59304135e+00 2.32993957e+01 6.85357058e+00 2.53742935e-01
 1.15763115e-01 7.01922514e-01 2.81210326e+01 2.10362836e+00
 8.69865112e+00 1.68370495e+02 2.16280519e+00 9.12046075e+01
 7.13400164e+00 9.18801155e+00]


In [72]:
# Minimum
print(data.min(axis=0))

[6.3200e-03 0.0000e+00 4.6000e-01 0.0000e+00 3.8500e-01 3.5610e+00
 2.9000e+00 1.1296e+00 1.0000e+00 1.8700e+02 1.2600e+01 3.2000e-01
 1.7300e+00 5.0000e+00]


In [73]:
# Maximum
print(data.max(axis=0))

[ 88.9762 100.      27.74     1.       0.871    8.78   100.      12.1265
  24.     711.      22.     396.9     37.97    50.    ]


In [74]:
# Calculate the 2.5 SD +/- range of the data
first_column = data[:, 0]
low = first_column.mean() - (first_column.std()*2.5)
high = first_column.mean() + (first_column.std()*2.5)
print(low, high)

-17.86907982092717 25.09612693555168


In [76]:
# Create a mask for the outliers
mask = np.logical_or(first_column > high, first_column < low)
print(mask)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

In [77]:
# Mask the data and check the values in the first column that are "outliers"
first_column[mask]

array([88.9762, 38.3518, 41.5292, 67.9208, 51.1358, 28.6558, 45.7461,
       25.9406, 73.5341, 37.6619])

In [79]:
# Modify data and save to disk
modified_data = data * 2
np.savetxt('modified_data.csv', modified_data)

In [81]:
# Check that the file was created!
! ls -lF modified_data.csv

-rw-r--r--  1 linweihung  staff  177100 Apr  6 00:59 modified_data.csv


In [82]:
# Load https://bit.ly/nds-python-mixed
data = np.loadtxt('https://bit.ly/nds-python-mixed', dtype=str)
print(data)

['"";"Hair";"FSIQ";"VIQ";"PIQ";"Weight";"Height";"MRI_Count"'
 '"1";"white";133;132;124;"118";"64.5";816932'
 '"2";"black";140;150;124;".";"72.5";1001121'
 '"3";"black";139;123;150;"143";"73.3";1038437'
 '"4";"black";133;129;128;"172";"68.8";965353'
 '"5";"white";137;132;134;"147";"65.0";951545'
 '"6";"white";99;90;110;"146";"69.0";928799'
 '"7";"white";138;136;131;"138";"64.5";991305'
 '"8";"white";92;90;98;"175";"66.0";854258'
 '"9";"black";89;93;84;"134";"66.3";904858'
 '"10";"black";133;114;147;"172";"68.8";955466'
 '"11";"white";132;129;124;"118";"64.5";833868'
 '"12";"black";141;150;128;"151";"70.0";1079549'
 '"13";"black";135;129;124;"155";"69.0";924059'
 '"14";"white";140;120;147;"155";"70.5";856472'
 '"15";"white";96;100;90;"146";"66.0";878897'
 '"16";"white";83;71;96;"135";"68.0";865363'
 '"17";"white";132;132;120;"127";"68.5";852244'
 '"18";"black";100;96;102;"178";"73.5";945088'
 '"19";"white";101;112;84;"136";"66.3";808020'
 '"20";"black";80;77;86;"180";"70.0";889083'
 '"2

In [83]:
# Check the loaded array's shape:
print(data.shape)

(41,)


In [86]:
# The columns are separated by semi-colons: we need to specify _that_, too!
data = np.loadtxt('https://bit.ly/nds-python-mixed', dtype = str, delimiter = ';')
print(data.shape)
print(data)

(41, 8)
[['""' '"Hair"' '"FSIQ"' '"VIQ"' '"PIQ"' '"Weight"' '"Height"'
  '"MRI_Count"']
 ['"1"' '"white"' '133' '132' '124' '"118"' '"64.5"' '816932']
 ['"2"' '"black"' '140' '150' '124' '"."' '"72.5"' '1001121']
 ['"3"' '"black"' '139' '123' '150' '"143"' '"73.3"' '1038437']
 ['"4"' '"black"' '133' '129' '128' '"172"' '"68.8"' '965353']
 ['"5"' '"white"' '137' '132' '134' '"147"' '"65.0"' '951545']
 ['"6"' '"white"' '99' '90' '110' '"146"' '"69.0"' '928799']
 ['"7"' '"white"' '138' '136' '131' '"138"' '"64.5"' '991305']
 ['"8"' '"white"' '92' '90' '98' '"175"' '"66.0"' '854258']
 ['"9"' '"black"' '89' '93' '84' '"134"' '"66.3"' '904858']
 ['"10"' '"black"' '133' '114' '147' '"172"' '"68.8"' '955466']
 ['"11"' '"white"' '132' '129' '124' '"118"' '"64.5"' '833868']
 ['"12"' '"black"' '141' '150' '128' '"151"' '"70.0"' '1079549']
 ['"13"' '"black"' '135' '129' '124' '"155"' '"69.0"' '924059']
 ['"14"' '"white"' '140' '120' '147' '"155"' '"70.5"' '856472']
 ['"15"' '"white"' '96' '100' '9

In [88]:
# Grand mean of the data
print(data.dtype)

<U11


In [89]:
# Import pandas and load https://bit.ly/nds-python-mixed
import pandas as pd
data = pd.read_csv('https://bit.ly/nds-python-mixed', delimiter = ';')
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [90]:
# Sneak peek at the first five rows of the data frame
data.head()

Unnamed: 0   Hair  FSIQ  VIQ  PIQ Weight Height  MRI_Count
0           1  white   133  132  124    118   64.5     816932
1           2  black   140  150  124      .   72.5    1001121
2           3  black   139  123  150    143   73.3    1038437
3           4  black   133  129  128    172   68.8     965353
4           5  white   137  132  134    147   65.0     951545

In [91]:
# Selecting one column:
hair = data["Hair"]
hair.head()

0    white
1    black
2    black
3    black
4    white
Name: Hair, dtype: object

In [94]:
# Selecting multiple columns:
hair_and_fsiq = data[["Hair","FSIQ"]]
print(hair_and_fsiq.head())
print(type(hair))
print(type(hair_and_fsiq))

    Hair  FSIQ
0  white   133
1  black   140
2  black   139
3  black   133
4  white   137
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [97]:
# We can specify the index when we load the data
data = pd.read_csv('https://bit.ly/nds-python-mixed', delimiter=';', index_col = 0)
data.head()

Hair  FSIQ  VIQ  PIQ Weight Height  MRI_Count
1  white   133  132  124    118   64.5     816932
2  black   140  150  124      .   72.5    1001121
3  black   139  123  150    143   73.3    1038437
4  black   133  129  128    172   68.8     965353
5  white   137  132  134    147   65.0     951545

In [107]:
# But we can also set the index directly, too:
data.index = ['participant_{}'.format(n+1) for n in range(len(data))]
data.head()

Hair  FSIQ  VIQ  PIQ Weight Height  MRI_Count
participant_1  white   133  132  124    118   64.5     816932
participant_2  black   140  150  124      .   72.5    1001121
participant_3  black   139  123  150    143   73.3    1038437
participant_4  black   133  129  128    172   68.8     965353
participant_5  white   137  132  134    147   65.0     951545

In [108]:
# Select participant number 10
data.loc['participant_10', 'Hair']

'black'

In [109]:
# Taking the mean of the data
data.mean()

/var/folders/1l/6zsyx5qd0yz1w5jk2423nczh0000gn/T/ipykernel_30264/3255083572.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.mean()


FSIQ            113.450
VIQ             112.350
PIQ             111.025
MRI_Count    908755.000
dtype: float64

In [110]:
# We can also use a special dataframe method to get a lot of stats quickly:
data.describe()

FSIQ         VIQ        PIQ     MRI_Count
count   40.000000   40.000000   40.00000  4.000000e+01
mean   113.450000  112.350000  111.02500  9.087550e+05
std     24.082071   23.616107   22.47105  7.228205e+04
min     77.000000   71.000000   72.00000  7.906190e+05
25%     89.750000   90.000000   88.25000  8.559185e+05
50%    116.500000  113.000000  115.00000  9.053990e+05
75%    135.500000  129.750000  128.00000  9.500780e+05
max    144.000000  150.000000  150.00000  1.079549e+06

In [112]:
# Check the data type of Weight and Hight
print(data['Weight'].dtype, data['Height'].dtype)

object object


In [113]:
# Check the Weight column
print(data['Weight'])

participant_1     118
participant_2       .
participant_3     143
participant_4     172
participant_5     147
participant_6     146
participant_7     138
participant_8     175
participant_9     134
participant_10    172
participant_11    118
participant_12    151
participant_13    155
participant_14    155
participant_15    146
participant_16    135
participant_17    127
participant_18    178
participant_19    136
participant_20    180
participant_21      .
participant_22    186
participant_23    122
participant_24    132
participant_25    114
participant_26    171
participant_27    140
participant_28    187
participant_29    106
participant_30    159
participant_31    127
participant_32    191
participant_33    192
participant_34    181
participant_35    143
participant_36    153
participant_37    144
participant_38    139
participant_39    148
participant_40    179
Name: Weight, dtype: object


In [116]:
# Replace '.' with NaN
data = data.replace('.', np.nan)
data.head()

Hair  FSIQ  VIQ  PIQ Weight Height  MRI_Count
participant_1  white   133  132  124    118   64.5     816932
participant_2  black   140  150  124    NaN   72.5    1001121
participant_3  black   139  123  150    143   73.3    1038437
participant_4  black   133  129  128    172   68.8     965353
participant_5  white   137  132  134    147   65.0     951545

In [118]:
# Re-check the data type of Weight and Height
print(data['Weight'].dtype, data['Height'].dtype)

object object


In [120]:
# Cast Weight and Height to float
data['Weight'].astype(float)
data['Height'].astype(float)

participant_1     64.5
participant_2     72.5
participant_3     73.3
participant_4     68.8
participant_5     65.0
participant_6     69.0
participant_7     64.5
participant_8     66.0
participant_9     66.3
participant_10    68.8
participant_11    64.5
participant_12    70.0
participant_13    69.0
participant_14    70.5
participant_15    66.0
participant_16    68.0
participant_17    68.5
participant_18    73.5
participant_19    66.3
participant_20    70.0
participant_21     NaN
participant_22    76.5
participant_23    62.0
participant_24    68.0
participant_25    63.0
participant_26    72.0
participant_27    68.0
participant_28    77.0
participant_29    63.0
participant_30    66.5
participant_31    62.5
participant_32    67.0
participant_33    75.5
participant_34    69.0
participant_35    66.5
participant_36    66.5
participant_37    70.5
participant_38    64.5
participant_39    74.0
participant_40    75.5
Name: Height, dtype: float64

In [122]:
# Reload data specifying `na_values` and check Weight/Height dtype
data = pd.read_csv('https://bit.ly/nds-python-mixed', delimiter=';', index_col=0, na_values='.')
data.head()

Hair  FSIQ  VIQ  PIQ  Weight  Height  MRI_Count
1  white   133  132  124   118.0    64.5     816932
2  black   140  150  124     NaN    72.5    1001121
3  black   139  123  150   143.0    73.3    1038437
4  black   133  129  128   172.0    68.8     965353
5  white   137  132  134   147.0    65.0     951545

In [123]:
# Now Weight + Height should be included in our "describe" method:
data.describe()

FSIQ         VIQ        PIQ      Weight     Height     MRI_Count
count   40.000000   40.000000   40.00000   38.000000  39.000000  4.000000e+01
mean   113.450000  112.350000  111.02500  151.052632  68.525641  9.087550e+05
std     24.082071   23.616107   22.47105   23.478509   3.994649  7.228205e+04
min     77.000000   71.000000   72.00000  106.000000  62.000000  7.906190e+05
25%     89.750000   90.000000   88.25000  135.250000  66.000000  8.559185e+05
50%    116.500000  113.000000  115.00000  146.500000  68.000000  9.053990e+05
75%    135.500000  129.750000  128.00000  172.000000  70.500000  9.500780e+05
max    144.000000  150.000000  150.00000  192.000000  77.000000  1.079549e+06