In [ ]:
fruit_prices = {
    'apple': 0.65,
    'mango': 1.50,
    'strawberry': '$5/pint',
    'durian' : 'unavailable'
}

In [ ]:
fruit_prices['apple']

In [ ]:
fruit_prices['apple'] =1.00
fruit_prices

In [ ]:
a = 0
b = 0

if a> b:
    print('a is greater than b')
elif a == b:
    print('a is equal to b')
else:
    print('a is not greater than b')

In [ ]:
random_stuff
for element in random_stuff:
    print(element)

In [ ]:
double_stuff = [element * 2 for element in random_stuff]
double_stuff

In [ ]:
counter = 0
while counter < 5:
    print(counter)
    counter = counter +1

In [ ]:
# import..
import math
print(math.pi)

In [ ]:
# from .. import ..
from math import pi
print(pi)

In [ ]:
# from .. import .. as ..
from math import pi as PI
print(PI)

In [ ]:
# We'll need the random module for this
import random

def add_noise(x, mu, sd):
    """
    Adds gaussian noise to the input.
    
    Parameters
    ----------
    x : number
        The number to add noise to
    mu : float
        the mean of the gaussian noise distribution
    sd : float
        The standard deviation of the noise distribution
    """
    noisy = random.normalvariate(mu, sd) + x
    return noisy

In [ ]:
x = add_noise(10, 0, 1)
print(x)

In [ ]:
def add_noise_with_defaults(x, mu=0, sd=1):
    """
    Adds gaussian noise to the input.
    
    Parameters
    ----------
    x : number
        The number to add noise to
    mu : float, optional
        the mean of the gaussian noise distribution. Default: 0
    sd : float, optional
        The standard deviation of the noise distribution. Default: 1
    """
    noisy = random.normalvariate(mu, sd) + x
    return noisy

In [ ]:
add_noise_with_defaults(10, 10, 10)

In [ ]:
%time 2*2

In [ ]:
# Average time running the code
%timeit 2 * 2

In [ ]:
# Import numpy and get the help documentation for reshape
import numpy
numpy.reshape?

In [ ]:
# By convention, we assign numpy to the variable np for brevity
import numpy as np

In [ ]:
# Create an empty 10 x 10 array of zeros
array_zeros = np.zeros(shape=(10,10))
print(array_zeros)

In [ ]:
# Inspect the array: what can we learn about its dimentionality?
print(array_zeros.shape)

In [ ]:
# Its data type?
print(array_zeros.dtype)

In [ ]:
# Create a 1D numpy array with values 0 through 999
array_1d = np.arange(0,1000)
array_1d

In [ ]:
# Reshape our array to 100 x 10
array_2d = np.reshape(array_1d, (100,10))
array_2d

In [ ]:
# Multiply every value in our array by 2
array_times_2 = array_2d * 2
array_times_2

In [ ]:
# Innspect the first 2 elements of each of the first five rows
array_times_2[:5, :2]

In [ ]:
original = np.copy(array_times_2)
original

In [11]:
# Load the dataset at https://bit.ly/nds-python-pure
data = np.loadtxt('https://bit.ly/nds-python-pure')
print(data)
print(data.shape)
print(data.dtype)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]
(506, 14)
float64


In [12]:
# Take the mean of the data array
print(data.mean())
print(np.mean(data))

66.67816985036703
66.67816985036703


In [ ]:
# Take the mean across the *first axis* (i.e., the mean across rows)
data.mean(axis=0)

In [ ]:
# Standard deviation
print(data.std(axis=0))

In [ ]:
# Minimum
print(data.min(axis=0))

In [ ]:
# Maximum
print(data.max(axis=0))

In [ ]:
# Calculate the 2.5 SD +/- range of the data
first_column = data[:, 0]
low = first_column.mean() - (first_column.std()*2.5)
high = first_column.mean() + (first_column.std()*2.5)
print(low, high)

In [ ]:
# Create a mask for the outliers
mask = np.logical_or(first_column > high, first_column < low)
print(mask)

In [ ]:
# Mask the data and check the values in the first column that are "outliers"
first_column[mask]

In [ ]:
# Modify data and save to disk
modified_data = data * 2
np.savetxt('modified_data.csv', modified_data)

In [ ]:
# Check that the file was created!
! ls -lF modified_data.csv

In [ ]:
# Load https://bit.ly/nds-python-mixed
data = np.loadtxt('https://bit.ly/nds-python-mixed', dtype=str)
print(data)

In [ ]:
# Check the loaded array's shape:
print(data.shape)

In [ ]:
# The columns are separated by semi-colons: we need to specify _that_, too!
data = np.loadtxt('https://bit.ly/nds-python-mixed', dtype = str, delimiter = ';')
print(data.shape)
print(data)

In [ ]:
# Grand mean of the data
print(data.dtype)

In [14]:
# Import pandas and load https://bit.ly/nds-python-mixed
import pandas as pd
data = pd.read_csv('https://bit.ly/nds-python-mixed', delimiter = ';')
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
# Sneak peek at the first five rows of the data frame
data.head()

In [ ]:
# Selecting one column:
hair = data["Hair"]
hair.head()

In [ ]:
# Selecting multiple columns:
hair_and_fsiq = data[["Hair","FSIQ"]]
print(hair_and_fsiq.head())
print(type(hair))
print(type(hair_and_fsiq))

In [15]:
# We can specify the index when we load the data
data = pd.read_csv('https://bit.ly/nds-python-mixed', delimiter=';', index_col = 0)
data.head()

Hair  FSIQ  VIQ  PIQ Weight Height  MRI_Count
1  white   133  132  124    118   64.5     816932
2  black   140  150  124      .   72.5    1001121
3  black   139  123  150    143   73.3    1038437
4  black   133  129  128    172   68.8     965353
5  white   137  132  134    147   65.0     951545

In [16]:
# But we can also set the index directly, too:
data.index = ['participant_{}'.format(n+1) for n in range(len(data))]
data.head()

Hair  FSIQ  VIQ  PIQ Weight Height  MRI_Count
participant_1  white   133  132  124    118   64.5     816932
participant_2  black   140  150  124      .   72.5    1001121
participant_3  black   139  123  150    143   73.3    1038437
participant_4  black   133  129  128    172   68.8     965353
participant_5  white   137  132  134    147   65.0     951545

In [ ]:
# Select participant number 10
data.loc['participant_10', 'Hair']

In [17]:
# Taking the mean of the data
data.mean()

/var/folders/1l/6zsyx5qd0yz1w5jk2423nczh0000gn/T/ipykernel_67381/3255083572.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.mean()


FSIQ            113.450
VIQ             112.350
PIQ             111.025
MRI_Count    908755.000
dtype: float64

In [ ]:
# We can also use a special dataframe method to get a lot of stats quickly:
data.describe()

In [18]:
# Check the data type of Weight and Hight
print(data['Weight'].dtype, data['Height'].dtype)

object object


In [19]:
# Check the Weight column
print(data['Weight'])

participant_1     118
participant_2       .
participant_3     143
participant_4     172
participant_5     147
participant_6     146
participant_7     138
participant_8     175
participant_9     134
participant_10    172
participant_11    118
participant_12    151
participant_13    155
participant_14    155
participant_15    146
participant_16    135
participant_17    127
participant_18    178
participant_19    136
participant_20    180
participant_21      .
participant_22    186
participant_23    122
participant_24    132
participant_25    114
participant_26    171
participant_27    140
participant_28    187
participant_29    106
participant_30    159
participant_31    127
participant_32    191
participant_33    192
participant_34    181
participant_35    143
participant_36    153
participant_37    144
participant_38    139
participant_39    148
participant_40    179
Name: Weight, dtype: object


In [20]:
# Replace '.' with NaN
data = data.replace('.', np.nan)
data.head()

Hair  FSIQ  VIQ  PIQ Weight Height  MRI_Count
participant_1  white   133  132  124    118   64.5     816932
participant_2  black   140  150  124    NaN   72.5    1001121
participant_3  black   139  123  150    143   73.3    1038437
participant_4  black   133  129  128    172   68.8     965353
participant_5  white   137  132  134    147   65.0     951545

In [ ]:
# Re-check the data type of Weight and Height
print(data['Weight'].dtype, data['Height'].dtype)

In [ ]:
# Cast Weight and Height to float
data['Weight'].astype(float)
data['Height'].astype(float)

In [21]:
# Reload data specifying `na_values` and check Weight/Height dtype
data = pd.read_csv('https://bit.ly/nds-python-mixed', delimiter=';', index_col=0, na_values='.')
data.head()

Hair  FSIQ  VIQ  PIQ  Weight  Height  MRI_Count
1  white   133  132  124   118.0    64.5     816932
2  black   140  150  124     NaN    72.5    1001121
3  black   139  123  150   143.0    73.3    1038437
4  black   133  129  128   172.0    68.8     965353
5  white   137  132  134   147.0    65.0     951545

In [22]:
# Now Weight + Height should be included in our "describe" method:
data.describe()

FSIQ         VIQ        PIQ      Weight     Height     MRI_Count
count   40.000000   40.000000   40.00000   38.000000  39.000000  4.000000e+01
mean   113.450000  112.350000  111.02500  151.052632  68.525641  9.087550e+05
std     24.082071   23.616107   22.47105   23.478509   3.994649  7.228205e+04
min     77.000000   71.000000   72.00000  106.000000  62.000000  7.906190e+05
25%     89.750000   90.000000   88.25000  135.250000  66.000000  8.559185e+05
50%    116.500000  113.000000  115.00000  146.500000  68.000000  9.053990e+05
75%    135.500000  129.750000  128.00000  172.000000  70.500000  9.500780e+05
max    144.000000  150.000000  150.00000  192.000000  77.000000  1.079549e+06